### ISSUE TITLE
rummage soundcloud data :raccoon: 

### ISSUE THREAD

**Issue by natesheehan** [natesheehan/loose-lips-2.0#3]
Summary:

    Scrape Soundcloud data and output as JSON file

Description:

- [ ]     Collect data from Soundcloud, including title, date, image, track URL, description, primary tag, and secondary tags
- [ ]     Output the collected data into a JSON file

 :raccoon:

**Comment by natesheehan** [comment]
@Lewisthiverval do you think we can close this ticket given the latest merge?

**Comment by Lewisthiverval** [comment]
Yep definitely
