### ISSUE TITLE
Recommended Posts Bug

### ISSUE THREAD

**Issue by natesheehan** [natesheehan/loose-lips-2.0#31]
A strange lil thing happens when you:
- are on the home page
- click on a post
- return back to the home page 

Looks like the recommended posts page styling shrinks to the global css of the blog post and all the posts are loaded instead of the 20 limit. 

Might also be related too #28

**Comment by Lewisthiverval** [comment]
3 Recommended posts are now below each individual posts, depending on the tags.  Closing for now but will need styling + additional tag filtering with new tag list that Fred will provide
