### ISSUE TITLE
Create suggested blog component 

### ISSUE THREAD

**Issue by natesheehan** [natesheehan/loose-lips-2.0#8]
Description: Freds has asked to have content recommended at the end of the blog post. We can do this by filtering and matching tags and serving that content, limit to 3 random. No user personalisation yet. 

---

ToDo:
- [ ] Create blog component 
- [ ] Add blog component to blog template

**Comment by natesheehan** [comment]
Same for this one, can we close this ticket now we have the recommended module on the home page?

**Comment by Lewisthiverval** [comment]
The component has been created but the logic behind the recommended selection is not done yet. so maybe best to leave this open for now?
